---
- name: 패키지 설치 - "{{ package }}"
  yum:
    name: "{{ package }}"
    state: latest

- name: 서비스 기동 -
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ service }}"