---
#Play1
#1) 패키지 설치 - httpd, mod_ssl, firewalld
#2) 웹서비스 설정 - /var/www/html/index.html
#3) 서비스 기동 - httpd, firewalld
#4) 방화벽 등록- http, https
#Paly2 -local host
#1) 웹요청 확인- curl http://web1.exalmple.com
#Play1
- name: 웹서버 설정과 확인
  hosts: web1
  tasks:
#1) 패키지 설치 - httpd, mod_ssl, firewalld
  - name: 1)페키지 설치 - httpd, mod_ssl, firewalld
    yum:
      name:
        - httpd
        - mod_ssl
        - firewalld
      state: latest
#2) 웹서비스 설정 - /var/www/html/index.html
  - name: 2) 웹서비스 설정 - /var/www/html/index.html
    copy:
      content: |
        <html>
        <h1><center>web1.example.com</center></h1>
        </html>
      dest: /var/www/html/index.html
#3) 서비스 기동 - httpd, firewalld
  - name: "(3)서비스 기동 -httpd , firewalld"
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - httpd
      - firewalld

#4) 방화벽 등록- http, https
  - name: "(4) 방화벽 등록- http, https"
    firewalld:
      port: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    loop:
      - 80/tcp
      - 443/tcp
#Paly2 -local host
- name: 웹 요청
  hosts: localhost
  become: no
  tasks: 
#1) 웹요청 확인- curl http://web1.exalmple.com
    - name: "(1) 웹요청 확인- curl http://web1.exalmple.com"
      uri:
        url: http://web1.exalmple.com
        return_content: true
        status_code: 200