---
#(1) 방화벽 서비스 Off -http(80/tcp)(443/tcp)
#(2) 서비스 OFF - httpd
#(3) 서비스 설정 삭제 - /var/www/html/imdex.btml => file
#(4) 패키지 삭제 - httpd, mod_ssl => yum


- name: "복원 작업"
  hosts: all
  tasks:
#(1) 방화벽 서비스 Off -http(80/tcp)(443/tcp)
  - name: "(1) 방화벽 서비스 Off -http(80/tcp)(443/tcp)"
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: disabled
    loop:
      - http
      - httpd
#(2) 서비스 OFF - httpd
  - name: "(2)서비스 OFF - httpd"
    service: 
      name: httpd
      state: stopped
#(3) 서비스 설정 삭제 - /var/www/html/imdex.html => file
  - name: "(3) 서비스 설정 삭제 - /var/www/html/imdex.html "
    file:
      path: /var/www/html/index.html
      state: absent
#(4) 패키지 삭제 - httpd, mod_ssl => yum
  - name: "(4) 패키지 삭제 - httpd, mod_ssl => yum"
    yum:
      name: httpd
      state: absent