---
- name: webserver
  hosts: webservers
  tasks:
  - name: install packages
    yum:
      name: 
      - http
      - mod_ssl
      - firewalld
      state: latest
  - name: start the service - httpd. firewalld
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
    - httpd
    - firewalld
  
  - name: open the service port
    firewalld:
      service: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    with_items:
    - http
    - https
  - name: /var/www/html/hello.html
    copy:
      content: "Hello World form {{ ansible_fqdn }}\n"
      dest: /var/www/html/hello.html
    notify: restart_httpd
  handlers:
  - name: restart_httpd
    service:
      name: httpd
      state: restarted