---
- name: /etc/motd배포
  hosts: all
  tasks:
  - name: /etc/motd 파일을 4대의 서버에서 삭제하기
    file:
      path: /etc/motd
      state: absent

  - name:
    file:
      path: /etc/motd
      state: touch
#  - name:
#    shell:
#      cmd: '> /etc/motd'
