---
- name: 패키지 설치 예제
  hosts: lamp
  vars:
    firewall: firewalld
  tasks:
    - name: 변수 포함 (Include the variabel file)
      include_vars: vars/main.yml
  
    - name: 작업 포함(Include the database )
      include_tasks: tasks/main.yml
    - name: 최신버전 firewall 패키지 설치
      yum:
        name: "{{ firewall }}"
        state: latest
  
    - name: 방화벽 서비스 기동
      service:
        name: "{{ firewall }}"
        state: started
        enabled: yes
    - name: 방화벽에 웹서비스 개시 (expose)
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled
    - name: "{{ web_root }}/var/www/html/index.html"
      copy:
        content: "{{ ansible_fqdn }}{{ ansible_default_ipv4.address }}has been customized by Ansible\n"
        dest: "{{ wep_root }}/index.html"
