---
- name: 패키지 삭제 예제
  hosts: lamp
  vars:
    firewall: firewalld
  tasks:
  -name: 변수 포함 (Include the cariable file)
    include_vars: vars/vars.yml
  - name: "{{web_root }}index.html 파일 삭제"
    file:
      path: "{{ web_root }}/index.html"
      state: absent
  - name: 방화벽 웹서비스 삭제
    firewalld: 
      service: http
      permanent: yes
      immediate: yes
      state: disabled
  
  - name: Start the database service
    service:
      name: "{{ item }}"
      enabled: no
      state: stopped
   
    with_items:
    - "{{ ansible_local.custom.services.db_service }}"
    - "{{ ansible_local.custom.services.web_service }}"

  - naem: 패키지 삭제
    yum:
      name:
        - http
        - firewalld
      state: absent
