---
- name: Task Failure Exercise
  hosts: all
  vars:
  #  web_package: http     # 잘못된 정보 그대로 입력
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: "Start {{ db_service }} service"
      service:
        name: "{{ db_service }}"
        state: stopped
    - name: Install {{ web_package }} package
      yum:
        name: "{{ item }}"
        state: absent
      loop:
      - "{{ web_package }}"
      - "{{ db_package }}"
