---
- name: 잡 제어 플레이북 예제
  hosts: webservers
  gather_facts: yes
  vars_files:
  - vars/vars.yml
  tasks:

  - name: 시스템 사양 정검 - 메모리 &배포판
    fail:
      msg: "{{ ansible_hostname }}'s Minimum memory : 256M"
    when: 
      - ansible_memfree_mb <= 256
      - ansible_memfree_mb != 'CentOS'
  - name: 웹 최신 패키지 설치
    yum:
      name: "{{ packages }}"
      state: latest
  - name: 웹서비스 기동
    service: 
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items: 
    - "{{ services }}"
  
  - name: 웹서버 설정
    # files/index.html =>/var/www/html/index.html
    # files/localhost.key /etc/pki/tls/private/localhost.key
    # files/ localhosts.crt => /etc/pki/tls/certs/localhots/crt
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items: 
    -"{{ conf_files }}"
    notify: restart httpd
  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted
  


