---
# tasks file for roles/apache
- name: 패키지 설치
  yum:
    name:
    - httpd
    - mod_ssl
    - firewalld
    state: latest

- name: 웹서버 설정 - /var/www/html/index.html - index.html.j2
template::

- name: 서비스 기동
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_item:
  - httpd
  - firewalld
